from __future__ import annotations

import json
import importlib
from pathlib import Path
from types import SimpleNamespace

import pytest

from apps.api.app.services.computer_use_service import (
    ComputerUseAction,
    ComputerUseService,
    ComputerUseServiceError,
)

computer_use_service_module = importlib.import_module("apps.api.app.services.computer_use_service")


def _new_service(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> ComputerUseService:
    monkeypatch.setenv("UNIVERSAL_AUTOMATION_RUNTIME_DIR", str(tmp_path / "automation"))
    monkeypatch.setenv("GEMINI_MODEL_PRIMARY", "gemini-3.1-pro-preview")
    return ComputerUseService()


def _new_action(name: str = "click", args: dict[str, object] | None = None) -> ComputerUseAction:
    return ComputerUseAction(
        action_id="act_123456",
        name=name,
        args=args or {"x": 1},
        rationale="rationale",
        risk_level="medium",
        confirmation_reason=None,
        action_digest="digest123",
        require_confirmation=False,
        safety_decision="allow_auto_execute",
    )


def test_create_session_rejects_blank_instruction(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    service = _new_service(monkeypatch, tmp_path)

    with pytest.raises(ComputerUseServiceError) as exc:
        service.create_session(instruction="   ", actor="alice")

    assert exc.value.status_code == 422
    assert str(exc.value) == "instruction is required"


def test_create_session_rejects_non_gemini_model(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    service = _new_service(monkeypatch, tmp_path)

    with pytest.raises(ComputerUseServiceError) as exc:
        service.create_session(instruction="open page", actor="alice", model="gpt-4.1")

    assert exc.value.status_code == 422
    assert "Gemini models only" in str(exc.value)


def test_parse_bool_and_resolve_include_thoughts(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    service = _new_service(monkeypatch, tmp_path)

    assert service._parse_bool(" true ", False) is True
    assert service._parse_bool("OFF", True) is False
    assert service._parse_bool("unknown", True) is True

    monkeypatch.setenv("GEMINI_INCLUDE_THOUGHTS", "0")
    assert service._resolve_include_thoughts(True) is False
    monkeypatch.setenv("GEMINI_INCLUDE_THOUGHTS", "yes")
    assert service._resolve_include_thoughts(False) is True


def test_resolve_thinking_level_valid_and_invalid(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    service = _new_service(monkeypatch, tmp_path)
    monkeypatch.setattr(
        computer_use_service_module.genai_types,
        "ThinkingLevel",
        SimpleNamespace(HIGH="high-level", LOW="low-level"),
        raising=False,
    )

    monkeypatch.setenv("GEMINI_THINKING_LEVEL", "low")
    assert service._resolve_thinking_level() == "low-level"

    monkeypatch.setenv("GEMINI_THINKING_LEVEL", "not-valid")
    assert service._resolve_thinking_level() == "high-level"


def test_extract_action_from_response_prefers_function_call(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    service = _new_service(monkeypatch, tmp_path)
    response = SimpleNamespace(
        candidates=[
            SimpleNamespace(
                content=SimpleNamespace(
                    parts=[
                        SimpleNamespace(function_call=SimpleNamespace(name="click", args={"x": 12}))
                    ]
                )
            )
        ]
    )

    name, args, rationale = service._extract_action_from_response(response)

    assert name == "click"
    assert args == {"x": 12}
    assert rationale == "generated by gemini computer-use planner"


def test_extract_action_from_response_text_fallback(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    service = _new_service(monkeypatch, tmp_path)
    response = SimpleNamespace(text=" summarize this result ")

    name, args, rationale = service._extract_action_from_response(response)

    assert name == "manual_review"
    assert args == {"summary": "summarize this result"}
    assert rationale == "text-only fallback"


def test_extract_action_from_response_empty_fallback(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    service = _new_service(monkeypatch, tmp_path)

    name, args, rationale = service._extract_action_from_response(SimpleNamespace(text=None))

    assert name == "manual_review"
    assert args == {}
    assert rationale == "empty model response"


def test_classify_risk_branches(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    service = _new_service(monkeypatch, tmp_path)

    critical = service._classify_risk("delete", {}, "safe")
    high = service._classify_risk("click", {"note": "send now"}, "open page")
    medium = service._classify_risk("click", {}, "open page")
    low = service._classify_risk("inspect", {}, "open page")

    assert critical == ("critical", "action 'delete' is high impact")
    assert high == ("high", "instruction/args contain high-risk keywords")
    assert medium == ("medium", None)
    assert low == ("low", None)


def test_execute_with_playwright_script_missing(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    service = _new_service(monkeypatch, tmp_path)
    session = service.create_session(instruction="open", actor="alice")
    action = _new_action()

    service._playwright_executor_script = tmp_path / "missing.mjs"

    with pytest.raises(ComputerUseServiceError) as exc:
        service._execute_with_playwright(session=session, action=action, actor="alice")

    assert exc.value.status_code == 503
    assert "script not found" in str(exc.value)


def test_execute_with_playwright_subprocess_exception(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    service = _new_service(monkeypatch, tmp_path)
    session = service.create_session(instruction="open", actor="alice")
    action = _new_action()

    script = tmp_path / "executor.mjs"
    script.write_text("// stub", encoding="utf-8")
    service._playwright_executor_script = script

    def _raise(*args, **kwargs):
        raise OSError("node unavailable")

    monkeypatch.setattr(computer_use_service_module.subprocess, "run", _raise)

    with pytest.raises(ComputerUseServiceError) as exc:
        service._execute_with_playwright(session=session, action=action, actor="alice")

    assert exc.value.status_code == 503
    assert "playwright executor failed" in str(exc.value)


def test_execute_with_playwright_non_zero_returncode(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    service = _new_service(monkeypatch, tmp_path)
    session = service.create_session(instruction="open", actor="alice")
    action = _new_action()

    script = tmp_path / "executor.mjs"
    script.write_text("// stub", encoding="utf-8")
    service._playwright_executor_script = script

    monkeypatch.setattr(
        computer_use_service_module.subprocess,
        "run",
        lambda *a, **k: SimpleNamespace(returncode=2, stdout="", stderr="boom"),
    )

    with pytest.raises(ComputerUseServiceError) as exc:
        service._execute_with_playwright(session=session, action=action, actor="alice")

    assert exc.value.status_code == 502
    assert "non-zero status (2)" in str(exc.value)


def test_execute_with_playwright_invalid_json_stdout(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    service = _new_service(monkeypatch, tmp_path)
    session = service.create_session(instruction="open", actor="alice")
    action = _new_action()

    script = tmp_path / "executor.mjs"
    script.write_text("// stub", encoding="utf-8")
    service._playwright_executor_script = script

    monkeypatch.setattr(
        computer_use_service_module.subprocess,
        "run",
        lambda *a, **k: SimpleNamespace(returncode=0, stdout="not-json", stderr=""),
    )

    with pytest.raises(ComputerUseServiceError) as exc:
        service._execute_with_playwright(session=session, action=action, actor="alice")

    assert exc.value.status_code == 502
    assert str(exc.value) == "playwright executor returned invalid json"


def test_execute_with_playwright_invalid_payload_non_dict(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    service = _new_service(monkeypatch, tmp_path)
    session = service.create_session(instruction="open", actor="alice")
    action = _new_action()

    script = tmp_path / "executor.mjs"
    script.write_text("// stub", encoding="utf-8")
    service._playwright_executor_script = script

    monkeypatch.setattr(
        computer_use_service_module.subprocess,
        "run",
        lambda *a, **k: SimpleNamespace(returncode=0, stdout=json.dumps(["bad"]), stderr=""),
    )

    with pytest.raises(ComputerUseServiceError) as exc:
        service._execute_with_playwright(session=session, action=action, actor="alice")

    assert exc.value.status_code == 502
    assert str(exc.value) == "playwright executor returned invalid payload"


def test_execute_with_playwright_normalizes_evidence_fields(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    service = _new_service(monkeypatch, tmp_path)
    session = service.create_session(instruction="open", actor="alice")
    action = _new_action(args={"key": "value"})

    script = tmp_path / "executor.mjs"
    script.write_text("// stub", encoding="utf-8")
    service._playwright_executor_script = script

    payload = {
        "executor": "node-worker",
        "evidence": {
            "screens": "wrong",
            "clips": ["clip.mp4"],
            "network_summary": [],
            "dom_summary": {"title": "ok"},
            "replay_trace": "bad",
        },
    }
    monkeypatch.setattr(
        computer_use_service_module.subprocess,
        "run",
        lambda *a, **k: SimpleNamespace(returncode=0, stdout=json.dumps(payload), stderr=""),
    )

    result = service._execute_with_playwright(session=session, action=action, actor="alice")

    assert result["executor"] == "node-worker"
    assert result["evidence"] == {
        "screens": [],
        "clips": ["clip.mp4"],
        "network_summary": {},
        "dom_summary": {"title": "ok"},
        "replay_trace": {},
    }


def test_require_session_owned_session_and_action_branches(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    service = _new_service(monkeypatch, tmp_path)
    session = service.create_session(instruction="open", actor="owner")

    with pytest.raises(ComputerUseServiceError) as invalid_id:
        service._require_session("bad-id")
    assert invalid_id.value.status_code == 422

    with pytest.raises(ComputerUseServiceError) as missing:
        service._require_session("cus_" + "f" * 32)
    assert missing.value.status_code == 404

    with pytest.raises(ComputerUseServiceError) as ownership:
        service._require_owned_session(session.session_id, "other")
    assert ownership.value.status_code == 404

    with pytest.raises(ComputerUseServiceError) as action_missing:
        service._require_action(session.session_id, "act_missing", "owner")
    assert action_missing.value.status_code == 404


def test_read_evidence_skips_bad_lines(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    service = _new_service(monkeypatch, tmp_path)
    session = service.create_session(instruction="open", actor="alice")
    evidence_file = service._evidence_file(session.session_id)

    with evidence_file.open("a", encoding="utf-8") as handle:
        handle.write("not-json\n")
        handle.write(json.dumps(["array-not-dict"]) + "\n")
        handle.write("\n")
        handle.write(json.dumps({"event": "custom", "payload": {"ok": True}}) + "\n")

    data = service.read_evidence(session_id=session.session_id, actor="alice")

    assert data["sessionId"] == session.session_id
    assert data["eventCount"] == 2
    assert data["events"][0]["event"] == "session_created"
    assert data["events"][1]["event"] == "custom"
