import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import YAML from "yaml"

export type EnvContractVariable = {
  name: string
  section: string
  default: string | number | boolean
  required: boolean
  sensitive: boolean
  description: string
}

export type EnvContract = {
  version: number
  description?: string
  allow_undeclared_exact?: string[]
  allow_undeclared_prefixes?: string[]
  variables: EnvContractVariable[]
}

export type EnvGovernancePolicy = {
  automation_run_payload_mode: "strict"
}

export function contractPath(repoRoot = resolve(".")): string {
  return resolve(repoRoot, "configs/env/contract.yaml")
}

export function envGovernancePolicyPath(repoRoot = resolve(".")): string {
  return resolve(repoRoot, "configs/env/governance-policy.yaml")
}

export function loadContract(repoRoot = resolve("."), explicitPath?: string): EnvContract {
  const path = explicitPath ? resolve(explicitPath) : contractPath(repoRoot)
  const parsed = YAML.parse(readFileSync(path, "utf8")) as EnvContract
  if (!parsed || typeof parsed !== "object" || !Array.isArray(parsed.variables)) {
    throw new Error(`Invalid env contract: ${path}`)
  }
  return parsed
}

export function loadEnvGovernancePolicy(repoRoot = resolve(".")): EnvGovernancePolicy {
  const path = envGovernancePolicyPath(repoRoot)
  const parsed = YAML.parse(readFileSync(path, "utf8")) as Partial<EnvGovernancePolicy> | null
  return {
    automation_run_payload_mode:
      parsed?.automation_run_payload_mode === "strict" ? "strict" : "strict",
  }
}

export function validateEnvGovernancePolicy(policy: EnvGovernancePolicy): string[] {
  const errors: string[] = []
  if (policy.automation_run_payload_mode !== "strict") {
    errors.push("env governance policy: automation_run_payload_mode must be strict")
  }
  return errors
}

export function normalizeContract(contract: EnvContract): EnvContractVariable[] {
  return [...contract.variables].sort((a, b) => {
    if (a.section !== b.section) return a.section.localeCompare(b.section)
    return a.name.localeCompare(b.name)
  })
}

function normalizeDefault(value: unknown): string {
  if (value === null || value === undefined) return ""
  if (typeof value === "boolean") return value ? "true" : "false"
  return String(value)
}

function toSectionTitle(section: string): string {
  return section
    .split(/[_\-\s]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ")
}

export function renderEnvExample(contract: EnvContract): string {
  const lines: string[] = []
  lines.push("# Generated file. Do not edit directly.")
  lines.push("# Source: configs/env/contract.yaml")
  lines.push("# Regenerate: pnpm env:contract:generate")
  lines.push("# Validate : pnpm env:contract:check")
  lines.push("")

  let currentSection = ""
  for (const item of contract.variables) {
    if (item.section !== currentSection) {
      if (currentSection) lines.push("")
      currentSection = item.section
      lines.push(`# [${currentSection}] ${toSectionTitle(currentSection)}`)
    }
    lines.push(`# ${item.description}`)
    const policy = `${item.required ? "required" : "optional"}, ${item.sensitive ? "sensitive" : "non-sensitive"}`
    lines.push(`# policy: ${policy}`)
    lines.push(`${item.name}=${normalizeDefault(item.default)}`)
  }

  return `${lines.join("\n")}\n`
}

export function renderConfigurationDoc(contract: EnvContract): string {
  const variables = normalizeContract(contract)
  const lines: string[] = []
  lines.push("# Reference: Configuration")
  lines.push("")
  lines.push("Generated from `configs/env/contract.yaml`. Do not edit this file manually.")
  lines.push("")
  lines.push("| Name | Section | Required | Sensitive | Default | Description |")
  lines.push("| --- | --- | --- | --- | --- | --- |")

  for (const item of variables) {
    const defaultValue = normalizeDefault(item.default)
    const defaultDisplay = defaultValue === "" ? "(empty)" : `\`${defaultValue}\``
    lines.push(
      `| \`${item.name}\` | ${item.section} | ${item.required ? "yes" : "no"} | ${item.sensitive ? "yes" : "no"} | ${defaultDisplay} | ${item.description} |`
    )
  }

  lines.push("")
  return lines.join("\n")
}

export function validateContractShape(contract: EnvContract): string[] {
  const errors: string[] = []
  const seen = new Set<string>()
  if (typeof contract.version !== "number") {
    errors.push("version must be number")
  }
  if (!Array.isArray(contract.variables) || contract.variables.length === 0) {
    errors.push("variables must be non-empty array")
    return errors
  }

  for (const [index, item] of contract.variables.entries()) {
    const prefix = `variables[${index}]`
    if (!item.name || !/^[A-Z_][A-Z0-9_]*$/.test(item.name)) errors.push(`${prefix}.name invalid`)
    if (seen.has(item.name)) errors.push(`${prefix}.name duplicate: ${item.name}`)
    seen.add(item.name)

    if (!item.section || typeof item.section !== "string") errors.push(`${prefix}.section missing`)
    if (item.default === undefined) errors.push(`${prefix}.default missing`)
    if (typeof item.required !== "boolean") errors.push(`${prefix}.required must be boolean`)
    if (typeof item.sensitive !== "boolean") errors.push(`${prefix}.sensitive must be boolean`)
    if (!item.description) errors.push(`${prefix}.description missing`)
  }

  return errors
}
