export type ButtonBehaviorManifestEntry = {
  id: string
  view: "QuickLaunch" | "TaskCenter" | "FlowWorkshop" | "CommandGrid" | "HelpTour" | "Params"
  selector: string
  owner_suite:
    | "critical-buttons"
    | "first-use"
    | "command-grid"
    | "task-center"
    | "flow-workshop"
    | "params"
    | "help-tour"
    | "nonstub"
  criticality: "critical" | "high" | "medium"
  expected_effect: string
  assertion_type:
    | "aria-selected"
    | "visibility-toggle"
    | "text-visible"
    | "toast-visible"
    | "attribute-change"
    | "storage-change"
  case_id: string
}

export const BUTTON_BEHAVIOR_MANIFEST = [
  {
    id: "nav-tab-quick-launch",
    view: "QuickLaunch",
    selector: "data-testid=console-tab-quick-launch",
    owner_suite: "first-use",
    criticality: "critical",
    expected_effect:
      "Switches to the Quick Launch view and activates the matching primary navigation tab.",
    assertion_type: "aria-selected",
    case_id: "nav-quick-launch-selected",
  },
  {
    id: "nav-locale-en",
    view: "QuickLaunch",
    selector: "data-testid=header-locale-en",
    owner_suite: "first-use",
    criticality: "medium",
    expected_effect:
      "Switches the product UI to the English locale and persists the locale preference.",
    assertion_type: "storage-change",
    case_id: "nav-locale-en-selected",
  },
  {
    id: "nav-locale-zh-cn",
    view: "QuickLaunch",
    selector: "data-testid=header-locale-zh-cn",
    owner_suite: "first-use",
    criticality: "medium",
    expected_effect:
      "Switches the product UI to the zh-CN locale and persists the locale preference.",
    assertion_type: "storage-change",
    case_id: "nav-locale-zh-cn-selected",
  },
  {
    id: "nav-tab-task-center",
    view: "TaskCenter",
    selector: "data-testid=console-tab-task-center",
    owner_suite: "task-center",
    criticality: "critical",
    expected_effect: "Switches to the Task Center view and shows the Task Center panel.",
    assertion_type: "aria-selected",
    case_id: "nav-task-center-selected",
  },
  {
    id: "nav-tab-flow-workshop",
    view: "FlowWorkshop",
    selector: "data-testid=console-tab-flow-draft",
    owner_suite: "flow-workshop",
    criticality: "high",
    expected_effect: "Switches to the Flow Workshop view and shows the main workshop card.",
    assertion_type: "aria-selected",
    case_id: "nav-flow-workshop-selected",
  },
  {
    id: "taskcenter-tab-command-runs",
    view: "TaskCenter",
    selector: "data-testid=task-center-tab-command-runs",
    owner_suite: "task-center",
    criticality: "high",
    expected_effect:
      "Shows the command run records panel and hides the template run records panel.",
    assertion_type: "visibility-toggle",
    case_id: "taskcenter-command-runs-visible",
  },
  {
    id: "taskcenter-tab-template-runs",
    view: "TaskCenter",
    selector: "data-testid=task-center-tab-template-runs",
    owner_suite: "task-center",
    criticality: "high",
    expected_effect:
      "Shows the template run records panel and hides the command run records panel.",
    assertion_type: "visibility-toggle",
    case_id: "taskcenter-template-runs-visible",
  },
  {
    id: "quicklaunch-first-use-start-step",
    view: "QuickLaunch",
    selector: "data-testid=quick-launch-first-use-start",
    owner_suite: "first-use",
    criticality: "high",
    expected_effect:
      "Advances the first-use guide from the welcome step into the configuration step.",
    assertion_type: "text-visible",
    case_id: "quicklaunch-first-use-start-stage",
  },
  {
    id: "quicklaunch-first-use-locate-config",
    view: "QuickLaunch",
    selector: "data-testid=quick-launch-first-use-locate-config",
    owner_suite: "first-use",
    criticality: "high",
    expected_effect: "Returns the first-use guide to the configuration step from any later stage.",
    assertion_type: "text-visible",
    case_id: "quicklaunch-first-use-locate-config",
  },
  {
    id: "quicklaunch-enter-run-step",
    view: "QuickLaunch",
    selector: 'role=button[name="Configuration done, continue to run"]',
    owner_suite: "first-use",
    criticality: "high",
    expected_effect:
      "Moves the first-use guide into the run step and shows the run-stage instructions.",
    assertion_type: "text-visible",
    case_id: "quicklaunch-enter-run-stage",
  },
  {
    id: "quicklaunch-sidebar-toggle",
    view: "QuickLaunch",
    selector: "aria-label=Collapse parameter rail",
    owner_suite: "first-use",
    criticality: "medium",
    expected_effect: "Toggles the parameter rail between collapsed and expanded states.",
    assertion_type: "visibility-toggle",
    case_id: "quicklaunch-sidebar-toggle-panel",
  },
  {
    id: "commandgrid-category-frontend",
    view: "CommandGrid",
    selector: "data-testid=command-category-frontend",
    owner_suite: "command-grid",
    criticality: "high",
    expected_effect: "Filters the command card list to the Frontend category.",
    assertion_type: "text-visible",
    case_id: "commandgrid-filter-frontend",
  },
  {
    id: "commandgrid-category-maintenance",
    view: "CommandGrid",
    selector: "data-testid=command-category-maintenance",
    owner_suite: "command-grid",
    criticality: "high",
    expected_effect: "Filters the command card list to the Maintenance category.",
    assertion_type: "text-visible",
    case_id: "commandgrid-filter-maintenance",
  },
  {
    id: "commandgrid-category-pipeline",
    view: "CommandGrid",
    selector: 'role=tab[name^="Pipeline"]',
    owner_suite: "command-grid",
    criticality: "high",
    expected_effect: "Filters the command card list to the Pipeline category.",
    assertion_type: "text-visible",
    case_id: "commandgrid-filter-pipeline",
  },
  {
    id: "taskcenter-refresh-template-runs",
    view: "TaskCenter",
    selector: "data-testid=task-center-template-runs-refresh",
    owner_suite: "task-center",
    criticality: "high",
    expected_effect: "Triggers a refresh request for the template run records panel.",
    assertion_type: "toast-visible",
    case_id: "taskcenter-refresh-template-runs",
  },
  {
    id: "taskcenter-explain-run",
    view: "TaskCenter",
    selector: 'role=button[name="Explain this run"]',
    owner_suite: "task-center",
    criticality: "high",
    expected_effect: "Shows the failure explainer panel for the selected retained evidence run.",
    assertion_type: "text-visible",
    case_id: "taskcenter-explain-run-panel",
  },
  {
    id: "taskcenter-share-pack",
    view: "TaskCenter",
    selector: 'role=button[name="Share pack"]',
    owner_suite: "task-center",
    criticality: "high",
    expected_effect: "Shows the share pack panel for the selected retained evidence run.",
    assertion_type: "text-visible",
    case_id: "taskcenter-share-pack-panel",
  },
  {
    id: "taskcenter-compare-runs",
    view: "TaskCenter",
    selector: 'role=button[name="Compare runs"]',
    owner_suite: "task-center",
    criticality: "high",
    expected_effect:
      "Shows the compare panel so the operator can inspect the selected baseline-versus-candidate evidence view.",
    assertion_type: "text-visible",
    case_id: "taskcenter-compare-runs-panel",
  },
  {
    id: "taskcenter-review-workspace",
    view: "TaskCenter",
    selector: 'role=button[name="Review workspace"]',
    owner_suite: "task-center",
    criticality: "high",
    expected_effect: "Shows the local-first review workspace packet for the selected retained run.",
    assertion_type: "text-visible",
    case_id: "taskcenter-review-workspace-panel",
  },
  {
    id: "taskcenter-promotion-guidance",
    view: "TaskCenter",
    selector: 'role=button[name="Promotion guidance"]',
    owner_suite: "task-center",
    criticality: "medium",
    expected_effect:
      "Shows promotion guidance for the selected retained run after explanation, share, and compare context are available.",
    assertion_type: "text-visible",
    case_id: "taskcenter-promotion-guidance-panel",
  },
  {
    id: "commandgrid-run-command",
    view: "CommandGrid",
    selector: 'role=button[name="Run"]',
    owner_suite: "command-grid",
    criticality: "critical",
    expected_effect: "Calls the command run API and shows a submitted-success confirmation.",
    assertion_type: "toast-visible",
    case_id: "commandgrid-run-command-success",
  },
  {
    id: "flowworkshop-save-draft",
    view: "FlowWorkshop",
    selector: 'role=button[name="Save Draft"]',
    owner_suite: "flow-workshop",
    criticality: "high",
    expected_effect: "Saves the flow draft and shows a success confirmation.",
    assertion_type: "toast-visible",
    case_id: "flowworkshop-save-draft-success",
  },
  {
    id: "flowworkshop-replay-latest",
    view: "FlowWorkshop",
    selector: 'role=button[name="Replay Latest Flow"]',
    owner_suite: "flow-workshop",
    criticality: "critical",
    expected_effect: "Triggers replay for the latest flow and shows a success confirmation.",
    assertion_type: "toast-visible",
    case_id: "flowworkshop-replay-latest-success",
  },
  {
    id: "flowworkshop-replay-step",
    view: "FlowWorkshop",
    selector: 'role=button[name="Replay Step"]',
    owner_suite: "flow-workshop",
    criticality: "high",
    expected_effect: "Triggers a single-step replay and shows the step replay confirmation.",
    assertion_type: "toast-visible",
    case_id: "flowworkshop-replay-step-success",
  },
  {
    id: "flowworkshop-replay-from-step",
    view: "FlowWorkshop",
    selector: 'role=button[name="Resume"]',
    owner_suite: "flow-workshop",
    criticality: "high",
    expected_effect: "Resumes replay from the selected step and shows the resume confirmation.",
    assertion_type: "toast-visible",
    case_id: "flowworkshop-replay-from-step-success",
  },
  {
    id: "taskcenter-submit-waiting-input",
    view: "TaskCenter",
    selector: 'role=button[name="Submit"]',
    owner_suite: "task-center",
    criticality: "high",
    expected_effect: "Submits waiting input for a template run and resumes execution.",
    assertion_type: "toast-visible",
    case_id: "taskcenter-submit-waiting-input-success",
  },
  {
    id: "helptour-open-panel",
    view: "HelpTour",
    selector: "aria-label=Help",
    owner_suite: "help-tour",
    criticality: "medium",
    expected_effect: "Opens the help panel and shows guidance for the current view.",
    assertion_type: "text-visible",
    case_id: "helptour-open-panel",
  },
  {
    id: "helptour-restart-onboarding",
    view: "HelpTour",
    selector: "data-testid=help-panel-restart-onboarding",
    owner_suite: "help-tour",
    criticality: "medium",
    expected_effect: "Resets onboarding state and reopens the onboarding overlay.",
    assertion_type: "storage-change",
    case_id: "helptour-restart-onboarding",
  },
  {
    id: "params-base-url-input",
    view: "Params",
    selector: "data-testid=param-base-url-input",
    owner_suite: "params",
    criticality: "high",
    expected_effect: "Keeps the UIQ_BASE_URL input stable and updates the run configuration.",
    assertion_type: "attribute-change",
    case_id: "params-base-url-input",
  },
  {
    id: "params-toggle-register-password-visibility",
    view: "Params",
    selector: "data-testid=params-toggle-register-password-visibility",
    owner_suite: "params",
    criticality: "medium",
    expected_effect: "Toggles the registration password field between password and text modes.",
    assertion_type: "attribute-change",
    case_id: "params-toggle-register-password-visibility",
  },
  {
    id: "params-toggle-api-key-visibility",
    view: "Params",
    selector: "data-testid=params-toggle-api-key-visibility",
    owner_suite: "params",
    criticality: "medium",
    expected_effect: "Toggles the Gemini API key field between password and text modes.",
    assertion_type: "attribute-change",
    case_id: "params-toggle-api-key-visibility",
  },
  {
    id: "params-toggle-token-visibility",
    view: "Params",
    selector: "data-testid=params-toggle-token-visibility",
    owner_suite: "params",
    criticality: "medium",
    expected_effect: "Toggles the API token field between password and text modes.",
    assertion_type: "attribute-change",
    case_id: "params-toggle-token-visibility",
  },
] as const satisfies readonly ButtonBehaviorManifestEntry[]
