// Auto-generated by contracts/scripts/generate-client.ts. Do not edit manually.

import { requestJson } from "../core/request";



export async function getCommandTowerOverview(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/command-tower/overview`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function getCommandTowerLatestFlow(baseUrl: string, queryParams: { session_id?: string }, init?: RequestInit): Promise<unknown> {
  const searchParams = new URLSearchParams();
  if (queryParams.session_id !== undefined) {
    searchParams.append("session_id", String(queryParams.session_id));
  }
  const path = searchParams.size > 0 ? `/api/command-tower/latest-flow?${searchParams.toString()}` : `/api/command-tower/latest-flow`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function getCommandTowerLatestFlowDraft(baseUrl: string, queryParams: { session_id?: string }, init?: RequestInit): Promise<unknown> {
  const searchParams = new URLSearchParams();
  if (queryParams.session_id !== undefined) {
    searchParams.append("session_id", String(queryParams.session_id));
  }
  const path = searchParams.size > 0 ? `/api/command-tower/latest-flow-draft?${searchParams.toString()}` : `/api/command-tower/latest-flow-draft`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function patchCommandTowerLatestFlowDraft(baseUrl: string, queryParams: { session_id?: string }, init?: RequestInit): Promise<unknown> {
  const searchParams = new URLSearchParams();
  if (queryParams.session_id !== undefined) {
    searchParams.append("session_id", String(queryParams.session_id));
  }
  const path = searchParams.size > 0 ? `/api/command-tower/latest-flow-draft?${searchParams.toString()}` : `/api/command-tower/latest-flow-draft`;
  return requestJson(baseUrl, path, "PATCH", init);
}

export async function postCommandTowerReplayLatest(baseUrl: string, queryParams: { session_id?: string }, init?: RequestInit): Promise<unknown> {
  const searchParams = new URLSearchParams();
  if (queryParams.session_id !== undefined) {
    searchParams.append("session_id", String(queryParams.session_id));
  }
  const path = searchParams.size > 0 ? `/api/command-tower/replay-latest?${searchParams.toString()}` : `/api/command-tower/replay-latest`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function postCommandTowerOrchestrateFromArtifacts(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/command-tower/orchestrate-from-artifacts`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function postCommandTowerReplayLatestFromStep(baseUrl: string, queryParams: { session_id?: string }, init?: RequestInit): Promise<unknown> {
  const searchParams = new URLSearchParams();
  if (queryParams.session_id !== undefined) {
    searchParams.append("session_id", String(queryParams.session_id));
  }
  const path = searchParams.size > 0 ? `/api/command-tower/replay-latest-from-step?${searchParams.toString()}` : `/api/command-tower/replay-latest-from-step`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function postCommandTowerReplayLatestStep(baseUrl: string, queryParams: { session_id?: string }, init?: RequestInit): Promise<unknown> {
  const searchParams = new URLSearchParams();
  if (queryParams.session_id !== undefined) {
    searchParams.append("session_id", String(queryParams.session_id));
  }
  const path = searchParams.size > 0 ? `/api/command-tower/replay-latest-step?${searchParams.toString()}` : `/api/command-tower/replay-latest-step`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function getCommandTowerStepEvidence(baseUrl: string, queryParams: { step_id: string; session_id?: string }, init?: RequestInit): Promise<unknown> {
  const searchParams = new URLSearchParams();
  searchParams.append("step_id", String(queryParams.step_id));
  if (queryParams.session_id !== undefined) {
    searchParams.append("session_id", String(queryParams.session_id));
  }
  const path = searchParams.size > 0 ? `/api/command-tower/evidence?${searchParams.toString()}` : `/api/command-tower/evidence`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function getCommandTowerEvidenceTimeline(baseUrl: string, queryParams: { session_id?: string }, init?: RequestInit): Promise<unknown> {
  const searchParams = new URLSearchParams();
  if (queryParams.session_id !== undefined) {
    searchParams.append("session_id", String(queryParams.session_id));
  }
  const path = searchParams.size > 0 ? `/api/command-tower/evidence-timeline?${searchParams.toString()}` : `/api/command-tower/evidence-timeline`;
  return requestJson(baseUrl, path, "GET", init);
}



export const COMMAND_TOWER_API_OPERATIONS = [
  {
    "operationId": "getCommandTowerOverview",
    "method": "GET",
    "path": "/api/command-tower/overview"
  },
  {
    "operationId": "getCommandTowerLatestFlow",
    "method": "GET",
    "path": "/api/command-tower/latest-flow"
  },
  {
    "operationId": "getCommandTowerLatestFlowDraft",
    "method": "GET",
    "path": "/api/command-tower/latest-flow-draft"
  },
  {
    "operationId": "patchCommandTowerLatestFlowDraft",
    "method": "PATCH",
    "path": "/api/command-tower/latest-flow-draft"
  },
  {
    "operationId": "postCommandTowerReplayLatest",
    "method": "POST",
    "path": "/api/command-tower/replay-latest"
  },
  {
    "operationId": "postCommandTowerOrchestrateFromArtifacts",
    "method": "POST",
    "path": "/api/command-tower/orchestrate-from-artifacts"
  },
  {
    "operationId": "postCommandTowerReplayLatestFromStep",
    "method": "POST",
    "path": "/api/command-tower/replay-latest-from-step"
  },
  {
    "operationId": "postCommandTowerReplayLatestStep",
    "method": "POST",
    "path": "/api/command-tower/replay-latest-step"
  },
  {
    "operationId": "getCommandTowerStepEvidence",
    "method": "GET",
    "path": "/api/command-tower/evidence"
  },
  {
    "operationId": "getCommandTowerEvidenceTimeline",
    "method": "GET",
    "path": "/api/command-tower/evidence-timeline"
  }
] as const;

