// Auto-generated by contracts/scripts/generate-client.ts. Do not edit manually.

import { requestJson, requestText } from "../core/request";



export async function getRoot(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function getHealth(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/health/`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function getDiagnostics(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/health/diagnostics`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function getAlerts(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/health/alerts`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function getHealthMetrics(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/health/metrics`;
  return requestText(baseUrl, path, "GET", init);
}

export async function postRumMetric(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/health/rum`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function getMetrics(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/metrics`;
  return requestText(baseUrl, path, "GET", init);
}



export const HEALTH_API_OPERATIONS = [
  {
    "operationId": "getRoot",
    "method": "GET",
    "path": "/"
  },
  {
    "operationId": "getHealth",
    "method": "GET",
    "path": "/health/"
  },
  {
    "operationId": "getDiagnostics",
    "method": "GET",
    "path": "/health/diagnostics"
  },
  {
    "operationId": "getAlerts",
    "method": "GET",
    "path": "/health/alerts"
  },
  {
    "operationId": "getHealthMetrics",
    "method": "GET",
    "path": "/health/metrics"
  },
  {
    "operationId": "postRumMetric",
    "method": "POST",
    "path": "/health/rum"
  },
  {
    "operationId": "getMetrics",
    "method": "GET",
    "path": "/metrics"
  }
] as const;

