// Auto-generated by contracts/scripts/generate-client.ts. Do not edit manually.
import { http, HttpResponse } from "msw";

export const handlers = [
  http.get("/", async () => {
    return HttpResponse.json({
      operationId: "getRoot",
      mocked: true
    });
  }),

  http.get("/health/", async () => {
    return HttpResponse.json({
      operationId: "getHealth",
      mocked: true
    });
  }),

  http.get("/health/diagnostics", async () => {
    return HttpResponse.json({
      operationId: "getDiagnostics",
      mocked: true
    });
  }),

  http.get("/health/alerts", async () => {
    return HttpResponse.json({
      operationId: "getAlerts",
      mocked: true
    });
  }),

  http.get("/health/metrics", async () => {
    return HttpResponse.json({
      operationId: "getHealthMetrics",
      mocked: true
    });
  }),

  http.post("/health/rum", async () => {
    return HttpResponse.json({
      operationId: "postRumMetric",
      mocked: true
    });
  }),

  http.get("/metrics", async () => {
    return HttpResponse.json({
      operationId: "getMetrics",
      mocked: true
    });
  }),

  http.get("/api/csrf", async () => {
    return HttpResponse.json({
      operationId: "getCsrfToken",
      mocked: true
    });
  }),

  http.post("/api/register", async () => {
    return HttpResponse.json({
      operationId: "postRegisterUser",
      mocked: true
    });
  }),

  http.get("/api/automation/commands", async () => {
    return HttpResponse.json({
      operationId: "listAutomationCommands",
      mocked: true
    });
  }),

  http.get("/api/automation/tasks", async () => {
    return HttpResponse.json({
      operationId: "listAutomationTasks",
      mocked: true
    });
  }),

  http.get("/api/automation/tasks/{task_id}", async () => {
    return HttpResponse.json({
      operationId: "getAutomationTask",
      mocked: true
    });
  }),

  http.post("/api/automation/run", async () => {
    return HttpResponse.json({
      operationId: "runAutomationCommand",
      mocked: true
    });
  }),

  http.post("/api/automation/tasks/{task_id}/cancel", async () => {
    return HttpResponse.json({
      operationId: "cancelAutomationTask",
      mocked: true
    });
  }),

  http.post("/api/computer-use/sessions", async () => {
    return HttpResponse.json({
      operationId: "createComputerUseSession",
      mocked: true
    });
  }),

  http.post("/api/computer-use/sessions/{session_id}/preview", async () => {
    return HttpResponse.json({
      operationId: "previewComputerUseAction",
      mocked: true
    });
  }),

  http.post("/api/computer-use/sessions/{session_id}/confirm/{action_id}", async () => {
    return HttpResponse.json({
      operationId: "confirmComputerUseAction",
      mocked: true
    });
  }),

  http.post("/api/computer-use/sessions/{session_id}/execute/{action_id}", async () => {
    return HttpResponse.json({
      operationId: "executeComputerUseAction",
      mocked: true
    });
  }),

  http.get("/api/computer-use/sessions/{session_id}/evidence", async () => {
    return HttpResponse.json({
      operationId: "readComputerUseEvidence",
      mocked: true
    });
  }),

  http.post("/api/embeddings/batch", async () => {
    return HttpResponse.json({
      operationId: "createBatchEmbeddings",
      mocked: true
    });
  }),

  http.get("/api/sessions", async () => {
    return HttpResponse.json({
      operationId: "listSessions",
      mocked: true
    });
  }),

  http.post("/api/sessions/start", async () => {
    return HttpResponse.json({
      operationId: "startSession",
      mocked: true
    });
  }),

  http.post("/api/sessions/{session_id}/finish", async () => {
    return HttpResponse.json({
      operationId: "finishSession",
      mocked: true
    });
  }),

  http.get("/api/flows", async () => {
    return HttpResponse.json({
      operationId: "listFlows",
      mocked: true
    });
  }),

  http.post("/api/flows", async () => {
    return HttpResponse.json({
      operationId: "createFlow",
      mocked: true
    });
  }),

  http.post("/api/flows/import-latest", async () => {
    return HttpResponse.json({
      operationId: "importLatestFlow",
      mocked: true
    });
  }),

  http.get("/api/flows/{flow_id}", async () => {
    return HttpResponse.json({
      operationId: "getFlow",
      mocked: true
    });
  }),

  http.patch("/api/flows/{flow_id}", async () => {
    return HttpResponse.json({
      operationId: "patchFlow",
      mocked: true
    });
  }),

  http.get("/api/templates", async () => {
    return HttpResponse.json({
      operationId: "listTemplates",
      mocked: true
    });
  }),

  http.post("/api/templates", async () => {
    return HttpResponse.json({
      operationId: "createTemplate",
      mocked: true
    });
  }),

  http.post("/api/templates/import", async () => {
    return HttpResponse.json({
      operationId: "importTemplate",
      mocked: true
    });
  }),

  http.post("/api/templates/from-artifacts", async () => {
    return HttpResponse.json({
      operationId: "postTemplatesFromArtifacts",
      mocked: true
    });
  }),

  http.get("/api/templates/{template_id}", async () => {
    return HttpResponse.json({
      operationId: "getTemplate",
      mocked: true
    });
  }),

  http.patch("/api/templates/{template_id}", async () => {
    return HttpResponse.json({
      operationId: "patchTemplate",
      mocked: true
    });
  }),

  http.get("/api/templates/{template_id}/export", async () => {
    return HttpResponse.json({
      operationId: "exportTemplate",
      mocked: true
    });
  }),

  http.get("/api/templates/{template_id}/readiness", async () => {
    return HttpResponse.json({
      operationId: "getTemplateReadiness",
      mocked: true
    });
  }),

  http.post("/api/profiles/resolve", async () => {
    return HttpResponse.json({
      operationId: "resolveProfile",
      mocked: true
    });
  }),

  http.get("/api/profiles/studio", async () => {
    return HttpResponse.json({
      operationId: "getProfileTargetStudio",
      mocked: true
    });
  }),

  http.patch("/api/profiles/studio/profiles/{profile_name}", async () => {
    return HttpResponse.json({
      operationId: "updateProfileStudio",
      mocked: true
    });
  }),

  http.patch("/api/profiles/studio/targets/{target_name}", async () => {
    return HttpResponse.json({
      operationId: "updateTargetStudio",
      mocked: true
    });
  }),

  http.post("/api/reconstruction/preview", async () => {
    return HttpResponse.json({
      operationId: "previewReconstruction",
      mocked: true
    });
  }),

  http.post("/api/reconstruction/generate", async () => {
    return HttpResponse.json({
      operationId: "generateReconstruction",
      mocked: true
    });
  }),

  http.get("/api/runs", async () => {
    return HttpResponse.json({
      operationId: "listRuns",
      mocked: true
    });
  }),

  http.post("/api/runs", async () => {
    return HttpResponse.json({
      operationId: "createRun",
      mocked: true
    });
  }),

  http.get("/api/runs/{run_id}", async () => {
    return HttpResponse.json({
      operationId: "getRun",
      mocked: true
    });
  }),

  http.post("/api/runs/{run_id}/otp", async () => {
    return HttpResponse.json({
      operationId: "submitRunOtp",
      mocked: true
    });
  }),

  http.get("/api/runs/{run_id}/recover-plan", async () => {
    return HttpResponse.json({
      operationId: "getRunRecoveryPlan",
      mocked: true
    });
  }),

  http.post("/api/runs/{run_id}/cancel", async () => {
    return HttpResponse.json({
      operationId: "cancelRun",
      mocked: true
    });
  }),

  http.get("/api/evidence-runs", async () => {
    return HttpResponse.json({
      operationId: "listEvidenceRuns",
      mocked: true
    });
  }),

  http.get("/api/evidence-runs/latest", async () => {
    return HttpResponse.json({
      operationId: "getLatestEvidenceRun",
      mocked: true
    });
  }),

  http.get("/api/evidence-runs/{run_id}", async () => {
    return HttpResponse.json({
      operationId: "getEvidenceRun",
      mocked: true
    });
  }),

  http.get("/api/evidence-runs/{run_id}/compare/{candidate_run_id}", async () => {
    return HttpResponse.json({
      operationId: "compareEvidenceRuns",
      mocked: true
    });
  }),

  http.get("/api/evidence-runs/{run_id}/share-pack", async () => {
    return HttpResponse.json({
      operationId: "getEvidenceSharePack",
      mocked: true
    });
  }),

  http.get("/api/evidence-runs/{run_id}/explain", async () => {
    return HttpResponse.json({
      operationId: "explainEvidenceRunFailure",
      mocked: true
    });
  }),

  http.get("/api/evidence-runs/{run_id}/promotion-candidate", async () => {
    return HttpResponse.json({
      operationId: "getPromotionCandidate",
      mocked: true
    });
  }),

  http.get("/api/evidence-runs/{run_id}/review-workspace", async () => {
    return HttpResponse.json({
      operationId: "getHostedReviewWorkspace",
      mocked: true
    });
  }),

  http.get("/api/integrations/vonage/inbound-sms", async () => {
    return HttpResponse.json({
      operationId: "getVonageInboundSms",
      mocked: true
    });
  }),

  http.post("/api/integrations/vonage/inbound-sms", async () => {
    return HttpResponse.json({
      operationId: "postVonageInboundSms",
      mocked: true
    });
  }),

  http.get("/api/command-tower/overview", async () => {
    return HttpResponse.json({
      operationId: "getCommandTowerOverview",
      mocked: true
    });
  }),

  http.get("/api/command-tower/latest-flow", async () => {
    return HttpResponse.json({
      operationId: "getCommandTowerLatestFlow",
      mocked: true
    });
  }),

  http.get("/api/command-tower/latest-flow-draft", async () => {
    return HttpResponse.json({
      operationId: "getCommandTowerLatestFlowDraft",
      mocked: true
    });
  }),

  http.patch("/api/command-tower/latest-flow-draft", async () => {
    return HttpResponse.json({
      operationId: "patchCommandTowerLatestFlowDraft",
      mocked: true
    });
  }),

  http.post("/api/command-tower/replay-latest", async () => {
    return HttpResponse.json({
      operationId: "postCommandTowerReplayLatest",
      mocked: true
    });
  }),

  http.post("/api/command-tower/orchestrate-from-artifacts", async () => {
    return HttpResponse.json({
      operationId: "postCommandTowerOrchestrateFromArtifacts",
      mocked: true
    });
  }),

  http.post("/api/command-tower/replay-latest-from-step", async () => {
    return HttpResponse.json({
      operationId: "postCommandTowerReplayLatestFromStep",
      mocked: true
    });
  }),

  http.post("/api/command-tower/replay-latest-step", async () => {
    return HttpResponse.json({
      operationId: "postCommandTowerReplayLatestStep",
      mocked: true
    });
  }),

  http.get("/api/command-tower/evidence", async () => {
    return HttpResponse.json({
      operationId: "getCommandTowerStepEvidence",
      mocked: true
    });
  }),

  http.get("/api/command-tower/evidence-timeline", async () => {
    return HttpResponse.json({
      operationId: "getCommandTowerEvidenceTimeline",
      mocked: true
    });
  })
];
