// Auto-generated by contracts/scripts/generate-client.ts. Do not edit manually.

export async function requestJson(baseUrl: string, path: string, method: string, init?: RequestInit): Promise<unknown> {
  const response = await fetch(`${baseUrl}${path}`, {
    method,
    headers: {
      "content-type": "application/json",
      ...(init?.headers ?? {})
    },
    ...init
  });
  const text = await response.text();
  if (!response.ok) {
    throw new Error(`API request failed: ${response.status} ${response.statusText}`);
  }
  if (text.length === 0) {
    return undefined;
  }
  try {
    return JSON.parse(text);
  } catch {
    throw new Error(`API request expected JSON body but received non-JSON payload for ${method} ${path}`);
  }
}

export async function requestText(baseUrl: string, path: string, method: string, init?: RequestInit): Promise<string> {
  const response = await fetch(`${baseUrl}${path}`, {
    method,
    ...init
  });
  const text = await response.text();
  if (!response.ok) {
    throw new Error(`API request failed: ${response.status} ${response.statusText}`);
  }
  return text;
}
